server:
  servlet:
    context-path: /service-main
  port: 8502

spring:
  application:
    title: Tienda de Ropa
    version: v1
    name: Tienda de Ropa LunaStore

  datasource:
    url: "jdbc:mysql://localhost/db_lunastore"
    username: "root"
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
